default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: wishP0nd
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: birthday_email_development

test:
  <<: *default
  database: birthday_email_test

production:
  <<: *default
  database: who_is_doing_code_review_production
  username: who_is_doing_code_review
  password: <%= ENV['WHO_IS_DOING_CODE_REVIEW_DATABASE_PASSWORD'] %>
